### ISSUE TITLE
Save session cookies

### ISSUE THREAD

**Issue by lyeskin** [asamy/steam#11]
Hello man!

Does library support session saving?
If it doesn't support this, what is the easiest way to implement this?

My case in details:
I run the worker every minute and fetch trade offers. If there are "gift" and active trade offers, I accept them. But getting trade offers doesn't require you to be logged in, it's just a request with Steam API Key. I'm a bit confused of abusing login api, it may lead to short bans from Steam.

**Comment by lyeskin** [comment]
By the way, great work! The best such library for steam written in golang.

**Comment by asamy** [comment]
I don't know what you mean by session saving, if you mean whether the library saves the session key and uses it later, then yes, it generates a session id when you call login then saves it and uses it for functions that require it.

No you won't get banned from Steam using the login api, unless you are flooding it.  

BTW to refresh the session key, you can re-login every 30 minutes.  I am not sure the exact time the session key expires in, but 30 minutes have always worked fine for me.

(You don't have to login yes, in that case you can use `NewSessionWithAPIKey` if you already have the API Key, otherwise you need to login for the library to help you get it automatically, and that is via `GetWebAPIKey` and `RegisterWebAPIKey`).)

**Comment by lyeskin** [comment]
Oh, nice, didn't notice the `NewSessionWithAPIKey` method. It will work. Thank you!
